- name: Crear directorio php
  file:
    path: /home/ubuntu/Proyecto_cloud/php
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Levantar contenedor docker
  become_user: ubuntu
  command: docker compose up -d
  args:
    chdir: /home/ubuntu/Proyecto_cloud/php